using System;
using System.Collections.Generic;
using System.Globalization;
using System.Threading;

namespace BooruManager.Services;

public class LocalizationService
{
    private static LocalizationService? _instance;
    public static LocalizationService Instance => _instance ??= new LocalizationService();

    private string _currentLanguage = "en";
    private readonly Dictionary<string, Dictionary<string, string>> _translations;

    public event Action? LanguageChanged;

    public string CurrentLanguage
    {
        get => _currentLanguage;
        set
        {
            if (string.IsNullOrEmpty(value))
            {
                return;
            }

            if (_currentLanguage != value && _translations != null && _translations.ContainsKey(value))
            {
                _currentLanguage = value;
                LanguageChanged?.Invoke();
            }
        }
    }

    public IReadOnlyList<LanguageInfo> AvailableLanguages { get; }

    private LocalizationService()
    {
        _translations = new Dictionary<string, Dictionary<string, string>>
        {
            ["en"] = GetEnglishStrings(),
            ["it"] = GetItalianStrings(),
            ["es"] = GetSpanishStrings(),
            ["fr"] = GetFrenchStrings(),
            ["de"] = GetGermanStrings(),
            ["pt"] = GetPortugueseStrings(),
            ["ja"] = GetJapaneseStrings(),
            ["zh"] = GetChineseStrings()
        };

        var systemLang = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.ToLowerInvariant();
        _currentLanguage = _translations.ContainsKey(systemLang) ? systemLang : "en";

        AvailableLanguages = new List<LanguageInfo>
        {
            new("en", "English"),
            new("it", "Italiano"),
            new("es", "Español"),
            new("fr", "Français"),
            new("de", "Deutsch"),
            new("pt", "Português"),
            new("ja", "日本語"),
            new("zh", "中文")
        };
    }

    public string this[string key] => GetString(key);

    public string GetString(string key)
    {
        if (_translations.TryGetValue(_currentLanguage, out var langStrings))
        {
            if (langStrings.TryGetValue(key, out var value))
            {
                return value;
            }
        }

        if (_translations.TryGetValue("en", out var enStrings))
        {
            if (enStrings.TryGetValue(key, out var value))
            {
                return value;
            }
        }

        return key;
    }

    private static Dictionary<string, string> GetEnglishStrings() => new()
    {
        ["AppTitle"] = "Advanced Booru Manager",
        ["Search"] = "Search",
        ["Booru"] = "Booru",
        ["Tags"] = "Tags",
        ["Recent"] = "Recent",
        ["ClearHistory"] = "Clear history",
        ["Results"] = "Results",
        ["PerPage"] = "Per page",
        ["Sort"] = "Sort",
        ["MediaType"] = "Media type",
        ["Size"] = "Size",
        ["Rating"] = "Rating",
        ["Safe"] = "Safe",
        ["Questionable"] = "Questionable",
        ["Adult"] = "Adult",
        ["Filters"] = "Filters",
        ["MinScore"] = "Min score",
        ["MinWidth"] = "Min width",
        ["MinHeight"] = "Min height",
        ["MustInclude"] = "Must include",
        ["Exclude"] = "Exclude",
        ["ResetFilters"] = "Reset filters",
        ["Shuffle"] = "Shuffle",
        ["ExportCsv"] = "Export CSV",
        ["Account"] = "Account",
        ["Username"] = "Username",
        ["Password"] = "Password",
        ["ApiKey"] = "API Key",
        ["Login"] = "Login",
        ["Logout"] = "Logout",
        ["LoggedInAs"] = "Logged in as",
        ["CheckUpdates"] = "Check for updates",
        ["Browse"] = "Browse",
        ["Favorites"] = "Favorites",
        ["View"] = "View",
        ["ToggleFavorite"] = "Toggle favorite",
        ["ViewTags"] = "View tags",
        ["CopyPostUrl"] = "Copy post URL",
        ["CopyMediaUrl"] = "Copy media URL",
        ["CopyTags"] = "Copy tags",
        ["AddToFavorites"] = "Add to favorites",
        ["RemoveFromFavorites"] = "Remove from favorites",
        ["TagSelector"] = "Tag Selector",
        ["UseSelected"] = "Use selected",
        ["Close"] = "Close",
        ["NoTagsAvailable"] = "No tags available for this post.",
        ["Language"] = "Language",
        ["Settings"] = "Settings",
        ["SortNewest"] = "Date (newest)",
        ["SortLargest"] = "Size (largest)",
        ["SortHighestVotes"] = "Votes (highest)",
        ["MediaImages"] = "Images",
        ["MediaAnimated"] = "Animated images",
        ["MediaVideo"] = "Videos",
        ["SizeAll"] = "All sizes",
        ["SizeLarge"] = "Large (>2000px)",
        ["SizeMedium"] = "Medium (1000-2000px)",
        ["SizeSmall"] = "Small (<1000px)",
        ["OnlyFavorites"] = "Only favorites",
        ["Download"] = "Download",
        ["DownloadSelected"] = "Download selected",
        ["HidePost"] = "Hide post",
        ["UnhidePost"] = "Unhide post",
        ["ClearHidden"] = "Clear hidden",
        ["Selected"] = "selected",
        ["Slideshow"] = "Slideshow",
        ["EnableSlideshow"] = "Enable slideshow mode",
        ["Interval"] = "Interval (seconds)",
        ["Next"] = "Next",
        ["Previous"] = "Previous",
        ["Pause"] = "Pause",
        ["Resume"] = "Resume",
        ["SelectAll"] = "Select all",
        ["ClearSelection"] = "Clear selection",
        ["Hidden"] = "Hidden",
        ["TagSuggestions"] = "Tag suggestions",
        ["SettingsWindowTitle"] = "Settings",
        ["DownloadSettings"] = "Download Settings",
        ["SlideshowSettings"] = "Slideshow Settings",
        ["UISettings"] = "UI Settings",
        ["AdvancedSettings"] = "Advanced Settings",
        ["LanguageSettings"] = "Language Settings",
        ["DownloadFolder"] = "Download Folder",
        ["DownloadFolderPlaceholder"] = "Select a folder for downloads",
        ["Browse"] = "Browse",
        ["CreateSubfolders"] = "Create subfolders for each download",
        ["PreserveOriginalFilenames"] = "Preserve original filenames",
        ["ConfirmBeforeDownload"] = "Confirm before downloading",
        ["ShowDownloadNotifications"] = "Show download notifications",
        ["MaxConcurrentDownloads"] = "Max concurrent downloads",
        ["SlideshowIntervalSeconds"] = "Interval (seconds)",
        ["AutoStartSlideshow"] = "Auto-start slideshow on open",
        ["CardWidth"] = "Card width (px)",
        ["CardHeight"] = "Card height (px)",
        ["RequestTimeoutSeconds"] = "Request timeout (seconds)",
        ["CustomUserAgent"] = "Custom User Agent",
        ["UserAgentPlaceholder"] = "Leave empty for default",
        ["SelectDownloadFolder"] = "Select Download Folder",
        ["OpenSettings"] = "Settings"
    };

    private static Dictionary<string, string> GetItalianStrings() => new()
    {
        ["AppTitle"] = "Advanced Booru Manager",
        ["Search"] = "Cerca",
        ["Booru"] = "Booru",
        ["Tags"] = "Tag",
        ["Recent"] = "Recenti",
        ["ClearHistory"] = "Cancella cronologia",
        ["Results"] = "Risultati",
        ["PerPage"] = "Per pagina",
        ["Sort"] = "Ordina",
        ["MediaType"] = "Tipo media",
        ["Size"] = "Dimensione",
        ["Rating"] = "Rating",
        ["Safe"] = "Sicuro",
        ["Questionable"] = "Dubbio",
        ["Adult"] = "Adulti",
        ["Filters"] = "Filtri",
        ["MinScore"] = "Punteggio min",
        ["MinWidth"] = "Larghezza min",
        ["MinHeight"] = "Altezza min",
        ["MustInclude"] = "Deve includere",
        ["Exclude"] = "Escludi",
        ["ResetFilters"] = "Resetta filtri",
        ["Shuffle"] = "Mescola",
        ["ExportCsv"] = "Esporta CSV",
        ["Account"] = "Account",
        ["Username"] = "Username",
        ["Password"] = "Password",
        ["ApiKey"] = "API Key",
        ["Login"] = "Accedi",
        ["Logout"] = "Esci",
        ["LoggedInAs"] = "Connesso come",
        ["CheckUpdates"] = "Controlla aggiornamenti",
        ["Browse"] = "Sfoglia",
        ["Favorites"] = "Preferiti",
        ["View"] = "Visualizza",
        ["ToggleFavorite"] = "Cambia preferito",
        ["ViewTags"] = "Visualizza tag",
        ["CopyPostUrl"] = "Copia URL post",
        ["CopyMediaUrl"] = "Copia URL media",
        ["CopyTags"] = "Copia tag",
        ["AddToFavorites"] = "Aggiungi ai preferiti",
        ["RemoveFromFavorites"] = "Rimuovi dai preferiti",
        ["TagSelector"] = "Selettore Tag",
        ["UseSelected"] = "Usa selezionati",
        ["Close"] = "Chiudi",
        ["NoTagsAvailable"] = "Nessun tag disponibile per questo post.",
        ["Language"] = "Lingua",
        ["Settings"] = "Impostazioni",
        ["SortNewest"] = "Data (più recenti)",
        ["SortLargest"] = "Dimensione (più grandi)",
        ["SortHighestVotes"] = "Voti (più votati)",
        ["MediaImages"] = "Immagini",
        ["MediaAnimated"] = "Immagini animate",
        ["MediaVideo"] = "Video",
        ["SizeAll"] = "Tutte le dimensioni",
        ["SizeLarge"] = "Grandi (>2000px)",
        ["SizeMedium"] = "Medie (1000-2000px)",
        ["SizeSmall"] = "Piccole (<1000px)",
        ["OnlyFavorites"] = "Solo preferiti",
        ["Download"] = "Scarica",
        ["DownloadSelected"] = "Scarica selezionati",
        ["HidePost"] = "Nascondi post",
        ["UnhidePost"] = "Mostra post",
        ["ClearHidden"] = "Pulisci nascosti",
        ["Selected"] = "selezionati",
        ["Slideshow"] = "Presentazione",
        ["EnableSlideshow"] = "Abilita modalità presentazione",
        ["Interval"] = "Intervallo (secondi)",
        ["Next"] = "Successivo",
        ["Previous"] = "Precedente",
        ["Pause"] = "Pausa",
        ["Resume"] = "Riprendi",
        ["SelectAll"] = "Seleziona tutto",
        ["ClearSelection"] = "Deseleziona tutto",
        ["Hidden"] = "Nascosti",
        ["TagSuggestions"] = "Suggerimenti tag",
        ["SettingsWindowTitle"] = "Impostazioni",
        ["DownloadSettings"] = "Impostazioni Download",
        ["SlideshowSettings"] = "Impostazioni Presentazione",
        ["UISettings"] = "Impostazioni Interfaccia",
        ["AdvancedSettings"] = "Impostazioni Avanzate",
        ["LanguageSettings"] = "Impostazioni Lingua",
        ["DownloadFolder"] = "Cartella Download",
        ["DownloadFolderPlaceholder"] = "Seleziona una cartella per i download",
        ["Browse"] = "Sfoglia",
        ["CreateSubfolders"] = "Crea sottocartelle per ogni download",
        ["PreserveOriginalFilenames"] = "Mantieni nomi file originali",
        ["ConfirmBeforeDownload"] = "Conferma prima del download",
        ["ShowDownloadNotifications"] = "Mostra notifiche download",
        ["MaxConcurrentDownloads"] = "Download simultanei max",
        ["SlideshowIntervalSeconds"] = "Intervallo (secondi)",
        ["AutoStartSlideshow"] = "Avvia presentazione automaticamente",
        ["CardWidth"] = "Larghezza card (px)",
        ["CardHeight"] = "Altezza card (px)",
        ["RequestTimeoutSeconds"] = "Timeout richiesta (secondi)",
        ["CustomUserAgent"] = "User Agent personalizzato",
        ["UserAgentPlaceholder"] = "Vuoto per default",
        ["SelectDownloadFolder"] = "Seleziona Cartella Download",
        ["OpenSettings"] = "Impostazioni"
    };

    private static Dictionary<string, string> GetSpanishStrings() => new()
    {
        ["AppTitle"] = "Advanced Booru Manager",
        ["Search"] = "Buscar",
        ["Booru"] = "Booru",
        ["Tags"] = "Etiquetas",
        ["Recent"] = "Recientes",
        ["ClearHistory"] = "Borrar historial",
        ["Results"] = "Resultados",
        ["PerPage"] = "Por página",
        ["Sort"] = "Ordenar",
        ["MediaType"] = "Tipo de medio",
        ["Size"] = "Tamaño",
        ["Rating"] = "Clasificación",
        ["Safe"] = "Seguro",
        ["Questionable"] = "Cuestionable",
        ["Adult"] = "Adulto",
        ["Filters"] = "Filtros",
        ["MinScore"] = "Puntaje mín",
        ["MinWidth"] = "Ancho mín",
        ["MinHeight"] = "Alto mín",
        ["MustInclude"] = "Debe incluir",
        ["Exclude"] = "Excluir",
        ["ResetFilters"] = "Restablecer filtros",
        ["Shuffle"] = "Mezclar",
        ["ExportCsv"] = "Exportar CSV",
        ["Account"] = "Cuenta",
        ["Username"] = "Usuario",
        ["Password"] = "Contraseña",
        ["ApiKey"] = "API Key",
        ["Login"] = "Iniciar sesión",
        ["Logout"] = "Cerrar sesión",
        ["LoggedInAs"] = "Conectado como",
        ["CheckUpdates"] = "Buscar actualizaciones",
        ["Browse"] = "Explorar",
        ["Favorites"] = "Favoritos",
        ["View"] = "Ver",
        ["ToggleFavorite"] = "Alternar favorito",
        ["ViewTags"] = "Ver etiquetas",
        ["CopyPostUrl"] = "Copiar URL del post",
        ["CopyMediaUrl"] = "Copiar URL del medio",
        ["CopyTags"] = "Copiar etiquetas",
        ["AddToFavorites"] = "Añadir a favoritos",
        ["RemoveFromFavorites"] = "Quitar de favoritos",
        ["TagSelector"] = "Selector de Etiquetas",
        ["UseSelected"] = "Usar seleccionados",
        ["Close"] = "Cerrar",
        ["NoTagsAvailable"] = "No hay etiquetas disponibles para este post.",
        ["Language"] = "Idioma",
        ["Settings"] = "Configuración",
        ["SortNewest"] = "Fecha (más recientes)",
        ["SortLargest"] = "Tamaño (más grandes)",
        ["SortHighestVotes"] = "Votos (más votados)",
        ["MediaImages"] = "Imágenes",
        ["MediaAnimated"] = "Imágenes animadas",
        ["MediaVideo"] = "Videos",
        ["SizeAll"] = "Todos los tamaños",
        ["SizeLarge"] = "Grandes (>2000px)",
        ["SizeMedium"] = "Medianas (1000-2000px)",
        ["SizeSmall"] = "Pequeñas (<1000px)",
        ["OnlyFavorites"] = "Solo favoritos"
    };

    private static Dictionary<string, string> GetFrenchStrings() => new()
    {
        ["AppTitle"] = "Advanced Booru Manager",
        ["Search"] = "Rechercher",
        ["Booru"] = "Booru",
        ["Tags"] = "Tags",
        ["Recent"] = "Récents",
        ["ClearHistory"] = "Effacer l'historique",
        ["Results"] = "Résultats",
        ["PerPage"] = "Par page",
        ["Sort"] = "Trier",
        ["MediaType"] = "Type de média",
        ["Size"] = "Taille",
        ["Rating"] = "Classification",
        ["Safe"] = "Sûr",
        ["Questionable"] = "Questionnable",
        ["Adult"] = "Adulte",
        ["Filters"] = "Filtres",
        ["MinScore"] = "Score min",
        ["MinWidth"] = "Largeur min",
        ["MinHeight"] = "Hauteur min",
        ["MustInclude"] = "Doit inclure",
        ["Exclude"] = "Exclure",
        ["ResetFilters"] = "Réinitialiser les filtres",
        ["Shuffle"] = "Mélanger",
        ["ExportCsv"] = "Exporter CSV",
        ["Account"] = "Compte",
        ["Username"] = "Nom d'utilisateur",
        ["Password"] = "Mot de passe",
        ["ApiKey"] = "Clé API",
        ["Login"] = "Connexion",
        ["Logout"] = "Déconnexion",
        ["LoggedInAs"] = "Connecté en tant que",
        ["CheckUpdates"] = "Vérifier les mises à jour",
        ["Browse"] = "Parcourir",
        ["Favorites"] = "Favoris",
        ["View"] = "Voir",
        ["ToggleFavorite"] = "Basculer favori",
        ["ViewTags"] = "Voir les tags",
        ["CopyPostUrl"] = "Copier l'URL du post",
        ["CopyMediaUrl"] = "Copier l'URL du média",
        ["CopyTags"] = "Copier les tags",
        ["AddToFavorites"] = "Ajouter aux favoris",
        ["RemoveFromFavorites"] = "Retirer des favoris",
        ["TagSelector"] = "Sélecteur de Tags",
        ["UseSelected"] = "Utiliser la sélection",
        ["Close"] = "Fermer",
        ["NoTagsAvailable"] = "Aucun tag disponible pour ce post.",
        ["Language"] = "Langue",
        ["Settings"] = "Paramètres",
        ["SortNewest"] = "Date (plus récents)",
        ["SortLargest"] = "Taille (plus grands)",
        ["SortHighestVotes"] = "Votes (plus votés)",
        ["MediaImages"] = "Images",
        ["MediaAnimated"] = "Images animées",
        ["MediaVideo"] = "Vidéos",
        ["SizeAll"] = "Toutes les tailles",
        ["SizeLarge"] = "Grandes (>2000px)",
        ["SizeMedium"] = "Moyennes (1000-2000px)",
        ["SizeSmall"] = "Petites (<1000px)",
        ["OnlyFavorites"] = "Favoris seulement"
    };

    private static Dictionary<string, string> GetGermanStrings() => new()
    {
        ["AppTitle"] = "Advanced Booru Manager",
        ["Search"] = "Suchen",
        ["Booru"] = "Booru",
        ["Tags"] = "Tags",
        ["Recent"] = "Kürzlich",
        ["ClearHistory"] = "Verlauf löschen",
        ["Results"] = "Ergebnisse",
        ["PerPage"] = "Pro Seite",
        ["Sort"] = "Sortieren",
        ["MediaType"] = "Medientyp",
        ["Size"] = "Größe",
        ["Rating"] = "Bewertung",
        ["Safe"] = "Sicher",
        ["Questionable"] = "Fragwürdig",
        ["Adult"] = "Erwachsen",
        ["Filters"] = "Filter",
        ["MinScore"] = "Min. Punktzahl",
        ["MinWidth"] = "Min. Breite",
        ["MinHeight"] = "Min. Höhe",
        ["MustInclude"] = "Muss enthalten",
        ["Exclude"] = "Ausschließen",
        ["ResetFilters"] = "Filter zurücksetzen",
        ["Shuffle"] = "Mischen",
        ["ExportCsv"] = "CSV exportieren",
        ["Account"] = "Konto",
        ["Username"] = "Benutzername",
        ["Password"] = "Passwort",
        ["ApiKey"] = "API-Schlüssel",
        ["Login"] = "Anmelden",
        ["Logout"] = "Abmelden",
        ["LoggedInAs"] = "Angemeldet als",
        ["CheckUpdates"] = "Nach Updates suchen",
        ["Browse"] = "Durchsuchen",
        ["Favorites"] = "Favoriten",
        ["View"] = "Ansehen",
        ["ToggleFavorite"] = "Favorit umschalten",
        ["ViewTags"] = "Tags anzeigen",
        ["CopyPostUrl"] = "Post-URL kopieren",
        ["CopyMediaUrl"] = "Medien-URL kopieren",
        ["CopyTags"] = "Tags kopieren",
        ["AddToFavorites"] = "Zu Favoriten hinzufügen",
        ["RemoveFromFavorites"] = "Aus Favoriten entfernen",
        ["TagSelector"] = "Tag-Auswahl",
        ["UseSelected"] = "Auswahl verwenden",
        ["Close"] = "Schließen",
        ["NoTagsAvailable"] = "Keine Tags für diesen Post verfügbar.",
        ["Language"] = "Sprache",
        ["Settings"] = "Einstellungen",
        ["SortNewest"] = "Datum (neueste)",
        ["SortLargest"] = "Größe (größte)",
        ["SortHighestVotes"] = "Stimmen (höchste)",
        ["MediaImages"] = "Bilder",
        ["MediaAnimated"] = "Animierte Bilder",
        ["MediaVideo"] = "Videos",
        ["SizeAll"] = "Alle Größen",
        ["SizeLarge"] = "Groß (>2000px)",
        ["SizeMedium"] = "Mittel (1000-2000px)",
        ["SizeSmall"] = "Klein (<1000px)",
        ["OnlyFavorites"] = "Nur Favoriten"
    };

    private static Dictionary<string, string> GetPortugueseStrings() => new()
    {
        ["AppTitle"] = "Advanced Booru Manager",
        ["Search"] = "Pesquisar",
        ["Booru"] = "Booru",
        ["Tags"] = "Tags",
        ["Recent"] = "Recentes",
        ["ClearHistory"] = "Limpar histórico",
        ["Results"] = "Resultados",
        ["PerPage"] = "Por página",
        ["Sort"] = "Ordenar",
        ["MediaType"] = "Tipo de mídia",
        ["Size"] = "Tamanho",
        ["Rating"] = "Classificação",
        ["Safe"] = "Seguro",
        ["Questionable"] = "Questionável",
        ["Adult"] = "Adulto",
        ["Filters"] = "Filtros",
        ["MinScore"] = "Pontuação mín",
        ["MinWidth"] = "Largura mín",
        ["MinHeight"] = "Altura mín",
        ["MustInclude"] = "Deve incluir",
        ["Exclude"] = "Excluir",
        ["ResetFilters"] = "Redefinir filtros",
        ["Shuffle"] = "Embaralhar",
        ["ExportCsv"] = "Exportar CSV",
        ["Account"] = "Conta",
        ["Username"] = "Nome de usuário",
        ["Password"] = "Senha",
        ["ApiKey"] = "Chave API",
        ["Login"] = "Entrar",
        ["Logout"] = "Sair",
        ["LoggedInAs"] = "Conectado como",
        ["CheckUpdates"] = "Verificar atualizações",
        ["Browse"] = "Navegar",
        ["Favorites"] = "Favoritos",
        ["View"] = "Ver",
        ["ToggleFavorite"] = "Alternar favorito",
        ["ViewTags"] = "Ver tags",
        ["CopyPostUrl"] = "Copiar URL do post",
        ["CopyMediaUrl"] = "Copiar URL da mídia",
        ["CopyTags"] = "Copiar tags",
        ["AddToFavorites"] = "Adicionar aos favoritos",
        ["RemoveFromFavorites"] = "Remover dos favoritos",
        ["TagSelector"] = "Seletor de Tags",
        ["UseSelected"] = "Usar selecionados",
        ["Close"] = "Fechar",
        ["NoTagsAvailable"] = "Nenhuma tag disponível para este post.",
        ["Language"] = "Idioma",
        ["Settings"] = "Configurações",
        ["SortNewest"] = "Data (mais recentes)",
        ["SortLargest"] = "Tamanho (maiores)",
        ["SortHighestVotes"] = "Votos (mais votados)",
        ["MediaImages"] = "Imagens",
        ["MediaAnimated"] = "Imagens animadas",
        ["MediaVideo"] = "Vídeos",
        ["SizeAll"] = "Todos os tamanhos",
        ["SizeLarge"] = "Grandes (>2000px)",
        ["SizeMedium"] = "Médias (1000-2000px)",
        ["SizeSmall"] = "Pequenas (<1000px)",
        ["OnlyFavorites"] = "Apenas favoritos"
    };

    private static Dictionary<string, string> GetJapaneseStrings() => new()
    {
        ["AppTitle"] = "Advanced Booru Manager",
        ["Search"] = "検索",
        ["Booru"] = "Booru",
        ["Tags"] = "タグ",
        ["Recent"] = "最近",
        ["ClearHistory"] = "履歴をクリア",
        ["Results"] = "結果",
        ["PerPage"] = "ページ당",
        ["Sort"] = "並べ替え",
        ["MediaType"] = "メディアタイプ",
        ["Size"] = "サイズ",
        ["Rating"] = "レーティング",
        ["Safe"] = "セーフ",
        ["Questionable"] = "問題あり",
        ["Adult"] = "成人",
        ["Filters"] = "フィルター",
        ["MinScore"] = "最小スコア",
        ["MinWidth"] = "最小幅",
        ["MinHeight"] = "最小高さ",
        ["MustInclude"] = "必須タグ",
        ["Exclude"] = "除外タグ",
        ["ResetFilters"] = "フィルターをリセット",
        ["Shuffle"] = "シャッフル",
        ["ExportCsv"] = "CSVエクスポート",
        ["Account"] = "アカウント",
        ["Username"] = "ユーザー名",
        ["Password"] = "パスワード",
        ["ApiKey"] = "APIキー",
        ["Login"] = "ログイン",
        ["Logout"] = "ログアウト",
        ["LoggedInAs"] = "ログイン中",
        ["CheckUpdates"] = "アップデートを確認",
        ["Browse"] = "ブラウズ",
        ["Favorites"] = "お気に入り",
        ["View"] = "表示",
        ["ToggleFavorite"] = "お気に入りを切り替え",
        ["ViewTags"] = "タグを表示",
        ["CopyPostUrl"] = "投稿URLをコピー",
        ["CopyMediaUrl"] = "メディアURLをコピー",
        ["CopyTags"] = "タグをコピー",
        ["AddToFavorites"] = "お気に入りに追加",
        ["RemoveFromFavorites"] = "お気に入りから削除",
        ["TagSelector"] = "タグ選択",
        ["UseSelected"] = "選択を使用",
        ["Close"] = "閉じる",
        ["NoTagsAvailable"] = "この投稿にはタグがありません。",
        ["Language"] = "言語",
        ["Settings"] = "設定",
        ["SortNewest"] = "日付（新しい順）",
        ["SortLargest"] = "サイズ（大きい順）",
        ["SortHighestVotes"] = "投票（多い順）",
        ["MediaImages"] = "画像",
        ["MediaAnimated"] = "アニメーション画像",
        ["MediaVideo"] = "動画",
        ["SizeAll"] = "すべてのサイズ",
        ["SizeLarge"] = "大（2000px以上）",
        ["SizeMedium"] = "中（1000-2000px）",
        ["SizeSmall"] = "小（1000px未満）",
        ["OnlyFavorites"] = "お気に入りのみ"
    };

    private static Dictionary<string, string> GetChineseStrings() => new()
    {
        ["AppTitle"] = "Advanced Booru Manager",
        ["Search"] = "搜索",
        ["Booru"] = "Booru",
        ["Tags"] = "标签",
        ["Recent"] = "最近",
        ["ClearHistory"] = "清除历史",
        ["Results"] = "结果",
        ["PerPage"] = "每页",
        ["Sort"] = "排序",
        ["MediaType"] = "媒体类型",
        ["Size"] = "尺寸",
        ["Rating"] = "评级",
        ["Safe"] = "安全",
        ["Questionable"] = "可疑",
        ["Adult"] = "成人",
        ["Filters"] = "筛选",
        ["MinScore"] = "最小分数",
        ["MinWidth"] = "最小宽度",
        ["MinHeight"] = "最小高度",
        ["MustInclude"] = "必须包含",
        ["Exclude"] = "排除",
        ["ResetFilters"] = "重置筛选",
        ["Shuffle"] = "随机排序",
        ["ExportCsv"] = "导出CSV",
        ["Account"] = "账户",
        ["Username"] = "用户名",
        ["Password"] = "密码",
        ["ApiKey"] = "API密钥",
        ["Login"] = "登录",
        ["Logout"] = "登出",
        ["LoggedInAs"] = "已登录为",
        ["CheckUpdates"] = "检查更新",
        ["Browse"] = "浏览",
        ["Favorites"] = "收藏",
        ["View"] = "查看",
        ["ToggleFavorite"] = "切换收藏",
        ["ViewTags"] = "查看标签",
        ["CopyPostUrl"] = "复制帖子URL",
        ["CopyMediaUrl"] = "复制媒体URL",
        ["CopyTags"] = "复制标签",
        ["AddToFavorites"] = "添加到收藏",
        ["RemoveFromFavorites"] = "从收藏中移除",
        ["TagSelector"] = "标签选择器",
        ["UseSelected"] = "使用选中项",
        ["Close"] = "关闭",
        ["NoTagsAvailable"] = "此帖子没有可用标签。",
        ["Language"] = "语言",
        ["Settings"] = "设置",
        ["SortNewest"] = "日期（最新）",
        ["SortLargest"] = "尺寸（最大）",
        ["SortHighestVotes"] = "投票（最多）",
        ["MediaImages"] = "图片",
        ["MediaAnimated"] = "动画图片",
        ["MediaVideo"] = "视频",
        ["SizeAll"] = "所有尺寸",
        ["SizeLarge"] = "大（>2000px）",
        ["SizeMedium"] = "中（1000-2000px）",
        ["SizeSmall"] = "小（<1000px）",
        ["OnlyFavorites"] = "仅收藏"
    };
}

public record LanguageInfo(string Code, string DisplayName);
